### PR TITLE
organize into autoload folder

### PR DESCRIPTION
**Pull request by fent**
Been profiling vim plugins with `--startuptime` and found this to take longer compared to other plugins

3 samples, the time the plugin took to load is on the right in milliseconds:

    117.359  014.745
    094.665  014.502
    085.481  013.344

But, after organizing everything into an `autoload` folder, there's not much of a difference, and at one point is slower :/

    085.127  011.619
    123.371  017.023
    083.348  012.713

So I guess there are other things that are affecting its startup time more than this. Didn't know the difference would be so tiny, but I had already made the changes so I made this PR anyway. Your call.

### CODE REVIEW

**Comment by flemingfleming** [comment]
I think that the reason it didn't make much difference is that almost all the time is spent creating mappings. From vim's point of view, creating mappings is a slow task, because it needs to be done immediately. Functions (and commands) however don't take much effort to define; the interpreter doesn't need to do anything with the function body until the function is called. So we get a situation where the slowest to load plugins are generally those that create the most mappings (e.g. Fugitive has 6x more loc than this but loads 3x faster for me, and targets.vim with 1/2 unimpaired's loc  is famously about the slowest loading plugin there is because of the sheer number of mappings it creates.

**Comment by fent** [comment]
Maybe we can do something like only add mappings after the `VimEnter` event fires? According to the docs, it fires after all windows and buffers have been created and loaded. Kinda how this plugin does it

https://github.com/junegunn/vim-after-object#setting-up

Or maybe this is something that plugin managers should handle

**Comment by tpope** [comment]
Thanks for doing the research. The `VimEnter` thing seems more for users to define mappings, not to provide defaults. It runs synchronously so it would mean a net gain of zero.

**Comment by fent** [comment]
> It runs synchronously so it would mean a net gain of zero.

Yes but a user might prefer to see something drawn first, even with some lag time after, than to have that lag before they see something.

**Comment by tpope** [comment]
I have decided not to pursue the autoload at this time. Maybe after the next version drops. But I will try the VimEnter thing, as it will also fulfill another goal: enabling other plugins to customize `g:nremap`.

**Pull request closed without merging**
